rock paper scissors
kzgodka/Rock-Paper-Scissors pull request #1
Opened 2017-03-26 14:54 UTC by kzgodka

2017-03-26 20:19 UTC, matwjablonski requested changes

2017-03-26 20:19 UTC, matwjablonski commented on js/scripts.js
> +
remove two empty lines

2017-03-26 20:19 UTC, matwjablonski commented on js/scripts.js
> +	if (player.score == 10) {
`===` not `==`

2017-03-26 20:19 UTC, matwjablonski commented on js/scripts.js
> +	} else if (winnerIs == 'computer') {
`===` not `==`

2017-03-26 20:19 UTC, matwjablonski commented on js/scripts.js
> +	if (winnerIs == 'player') {
`===` not `==`

2017-03-26 20:19 UTC, matwjablonski commented on js/scripts.js
> +		(computerPick == 'rock' && playerPick == 'scissors') ||
`===` not `==`

2017-03-26 20:19 UTC, matwjablonski commented on js/scripts.js
> +		(computerPick == 'scissors' && playerPick == 'paper') ||
`===` not `==`

2017-03-26 20:19 UTC, matwjablonski commented on js/scripts.js
> +		(computerPick == 'paper' && playerPick == 'rock')) {
`===` not `==`

2017-03-26 20:19 UTC, matwjablonski commented on js/scripts.js
> +	}	else if (computer.score == 10) {
`===` not `==`

2017-03-27 19:19 UTC, kzgodka commented
changed '==' to '===' also added reset points after click 'jeszcze raz'

2017-03-31 19:57 UTC, kzgodka commented
added new function - reset points and choices

2017-04-01 09:02 UTC, matwjablonski approved these changes

2018-10-09 09:57 UTC, merged